# The Gears of Neural Networks: Tensor Operations

## Element-wise operations

In [3]:
# Naive relu operation
def naive_relu(x): 
    assert len(x.shape) == 2 # x is a 2D tensor 

    x = x.copy() # Avoid overwriting the input tensor
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

In [4]:
# Naive addition operation
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape # x and y are 2D tensors of same shape

    x = x.copy() # Avoid overwriting the input tensor
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [6]:
# Naive subtraction operation
def naive_sub(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape # x and y are 2D tensors of same shape

    x = x.copy() # Avoid overwriting the input tensor
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] -= y[i, j]
    return x

In [7]:
# Naive multiplication operation
def naive_mul(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape # x and y are 2D tensors of same shape

    x = x.copy() # Avoid overwriting the input tensor
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] *= y[i, j]
    return x

In [ ]:
# Element-wise operation using numpy
import numpy as np

z = x + y # Element-wise addition

z = np.maximum(z, 0.) # Element-wise relu

## Broadcasting

In [8]:
# Naive addition of 2 tensors of different shapes
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2 # x is a 2D Numpy tensor.
    assert len(y.shape) == 1 # y is a Numpy vector.
    assert x.shape[1] == y.shape[0]

    x = x.copy() # Avoid overwriting the input tensor.
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [10]:
# Elemente-wise maximum operation
import numpy as np

x = np.random.random((64, 3, 32, 10)) # x is a random tensor with shape (64, 3, 32, 10).
y = np.random.random((32, 10)) # y is a random tensor with shape (32, 10).

z = np.maximum(x, y) # The output z has shape (64, 3, 32, 10) like x.

print(z.shape)

(64, 3, 32, 10)


## Tensor Dot

In [12]:
import numpy as np
z = np.dot(x,y)

In [13]:
# Naive dot operation between two vectors
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1 
    assert x.shape[0] == y.shape[0] # x and y are Numpy vectors.

    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i] # dot operation applied for each element
    return z

In [14]:
# Naive dot operation between a matrix and a vector
def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2 # x is a Numpy matrix.
    assert len(y.shape) == 1 # y is a Numpy vector.
    assert x.shape[1] == y.shape[0] # The first dimension of x must be the same as the 0th dimension of y!

    # This operation returns a vector of 0s with the same shape as y.
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

# Alternative way using last block
def naive_matrix_vector_dot(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    return z

In [15]:
# Naive dot operation between two matrices
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2 # x and y are Numpy matrices.
    assert x.shape[1] == y.shape[0] # The first dimension of x must be the same as the 0th dimension of y!

    z = np.zeros((x.shape[0], y.shape[1])) # This operation returns a matrix of 0s with a specific shape.
    for i in range(x.shape[0]): # Iterates over the rows of x
        for j in range(y.shape[1]): # And over the colums of y
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

## Tensor Reshaping

In [16]:
x = np.array([[0., 1.], [2., 3.], [4., 5.]])
print(x.shape)

(3, 2)


In [17]:
x = x.reshape((6, 1))
print(x)

[[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]]


In [19]:
x = x.reshape((2,3))
print(x)

[[ 0.  1.  2.]
 [ 3.  4.  5.]]


In [20]:
x = np.zeros((300, 20)) # Creates an all-zeros matrix of shape (300, 20)
print(x.shape)
x = np.transpose(x)
print(x.shape)

(300, 20)
(20, 300)
